plugins {
	id 'dev.architectury.loom' version '1.13-SNAPSHOT' apply false
	id 'architectury-plugin' version '3.4-SNAPSHOT'
	id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
}

architectury {
	minecraft = project.minecraftVersion
}

allprojects {
	group = rootProject.group
	version = rootProject.modVersion
}

subprojects {
	apply plugin: 'dev.architectury.loom'
	apply plugin: 'architectury-plugin'

	base {
		archivesName = "$rootProject.name-$rootProject.minecraftVersion-$project.name"
	}

	repositories {
		maven {
			name = "CurseMaven"
			url = "https://www.cursemaven.com"
		}
		maven {
			name = "LadySnake"
			url = 'https://maven.ladysnake.org/releases'
		}
		exclusiveContent {
			forRepository {
				maven {
					name = "Modrinth"
					url = "https://api.modrinth.com/maven"
				}
			}
			filter {
				includeGroup "maven.modrinth"
			}
		}
	}

	dependencies {
		minecraft "net.minecraft:minecraft:$rootProject.minecraftVersion"
		mappings loom.officialMojangMappings()

		modImplementation("maven.modrinth:iceberg:1.2.10")
		modImplementation("maven.modrinth:legendary-tooltips:1.5.0")
		modImplementation("maven.modrinth:prism-lib:1.0.10")

		/*modImplementation("maven.modrinth:iceberg:1.2.10")
		modImplementation("maven.modrinth:legendary-tooltips:1.5.0")
		modImplementation("maven.modrinth:prism-lib:1.0.10")
		modImplementation "curse.maven:adorned-1036809:5515068"
		modImplementation "curse.maven:accessories-938917:5576244"
		modImplementation "curse.maven:accessoriestrinkets-1005680:5575593"
		modImplementation("org.ladysnake.cardinal-components-api:cardinal-components-base:6.1.0")
		modImplementation("org.ladysnake.cardinal-components-api:cardinal-components-entity:6.1.0")*/
	}

	java {
		// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
		// if it is present.
		// If you remove this line, sources will not be generated.
		withSourcesJar()

		sourceCompatibility = JavaVersion.VERSION_21
		targetCompatibility = JavaVersion.VERSION_21
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 21
	}
}